@dotnet_redfish_HostAddress = http://localhost:8080

GET {{dotnet_redfish_HostAddress}}/redfish/v1/
Accept: application/json

###

GET {{dotnet_redfish_HostAddress}}/redfish/v1/Chassis/
Accept: application/json

###
